server:
  port: 9000

spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB


  datasource:
    platform: mysql
    url:  jdbc:mysql://eob-db.cwdcdldpdi5b.ap-northeast-2.rds.amazonaws.com/EOB_Server?autoReconnect=true # 변경해주세요
    username:  eob
    password:  eob1234!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

cloud:
  aws:
    s3:
      bucket: eraofband
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      instanceProfile: true
