server:
  port: 9000

spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

cloud:
  aws:
    s3:
      bucket: eraofband
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
